version: '2'

services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=magento
    volumes:
      - 'magento_database:/var/lib/mysql'
  magento:
    image: 'jamesbrink/magento:2.2.3-sass'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=root
      - MAGENTO_DATABASE_PASSWORD=password
      - MAGENTO_DATABASE_NAME=magento
      - MAGENTO_ADMINURI=admin
      - MAGENTO_HOST=localhost
      - ENABLE_SAMPLE_DATA=true
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb

volumes:
  magento_database:
    driver: local